[book]
authors = ["Atlas Team"]
language = "ja"
multilingual = false
src = "src"
title = "有田市ふるさと納税 農家様向けマニュアル"

[output.html]
additional-css = ["atlas-common/theme/mdbook-admonish.css"]
additional-js = []
git-repository-url = "https://github.com/totototo0526/arida-farmer"
edit-url-template = "https://github.com/totototo0526/arida-farmer/edit/main/{path}"
theme = ".theme_build"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2"

[build]
build-dir = "book"
