[book]
authors = ["Atlas Team"]
language = "ja"
src = "src"
title = "有田市ふるさと納税 農家様向けマニュアル"

[output.html]
theme = ".theme_build"
git-repository-url = "https://github.com/totototo0526/arida-farmer"
edit-url-template = "https://github.com/totototo0526/arida-farmer/edit/main/{path}"
additional-css = ["atlas-common/theme/css/atlas-custom.css", "src/custom.css"]
additional-js = ["atlas-common/theme/atlas-alerts.js", "atlas-common/theme/elasticlunr-jp.js"]

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "book"
